# Generated by Django 6.0.4 on 2026-04-28 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Melodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=255)),
                ('fisier_original', models.FileField(upload_to='melodii_de_procesat/')),
                ('data_incarcare', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melodii', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('vocals', 'Vocals'), ('drums', 'Drums'), ('bass', 'Bass'), ('other', 'Other')], max_length=10)),
                ('fisier_stem', models.FileField(upload_to='separated/')),
                ('melodie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stemuri', to='app.melodie')),
            ],
        ),
    ]
