# Generated by Django 6.0.4 on 2026-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melodie',
            name='fisier_original',
            field=models.FileField(upload_to='originale/'),
        ),
    ]
