# Generated by Django 6.0.6 on 2026-06-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_melodie_fisier_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='stem',
            name='este_transformat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stem',
            name='instrument_tinta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stem',
            name='stem_parinte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformari', to='app.stem'),
        ),
        migrations.AlterField(
            model_name='stem',
            name='tip',
            field=models.CharField(choices=[('vocals', 'Vocals'), ('drums', 'Drums'), ('bass', 'Bass'), ('other', 'Other')], max_length=20),
        ),
    ]
